name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.0
          os: ubuntu-20.04
        - ruby: 2.7
          os: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec ruby extconf.rb
    - run: make
    - run: bundle exec ruby bench.rb
    - run: bundle exec ruby bench.rb
    - run: bundle exec ruby bench.rb
